### PR TITLE
The wiki commons android image link is dead

### PR DESCRIPTION
**Pull request by ThomasGHenry**
I updated this to the official google link.

### CODE REVIEW

**Comment by wyantb** [comment]
Hmm is there an SVG version of the google version that can be used instead here? When I tried pulling in the latest version the sizing of the two buttons was pretty different for me - how have you worked out the sizing?

**Comment by ThomasGHenry** [comment]
I don't remember now, but you are right about the size. I had to tend to
that manually, maybe by constraining the size of the container I used it in
or something like that. For me, it was better than nothing. If you find a
better alternative image to link to, the repo owner seems amenable to PRs.
Good luck!

**Comment by wyantb** [comment]
It's far easier in my case to pull down a version of the SVG and override background-image with an `!important`, unfortunately. Far easier to have two SVGs than try and convince the PNG on our page to size itself within it's container like the SVG (stretching to bounds etc). Thanks, though!

**Comment by ThomasGHenry** [comment]
Which SVG are you using?

**Comment by wyantb** [comment]
I'm using https://commons.wikimedia.org/wiki/File:Google_Play_Store_badge_EN.svg , raw file https://upload.wikimedia.org/wikipedia/commons/7/78/Google_Play_Store_badge_EN.svg

**Comment by ThomasGHenry** [comment]
Thanks!

**Pull request merged**
